server:
  port: 8888

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: mc-server
  datasource:
    dynamic:
      strict: false
      primary: core
      datasource:
        core:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://175.24.228.204:3306/mc_server?allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
          username: root
          password: root

mybatis-plus:
  mapper-locations: classpath*:mappings/*Mapper.xml

logging:
  level:
    module.dao: debug
    springfox.documentation.schema: error
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    module: DEBUG

# Sa-Token配置
sa-token:
  # token 名称 (同时也是cookie名称)
  token-name: satoken
  # token 有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token 临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

# swagger 接口文档配置
swagger:
  title: MC服务
  description: MC服务
  version: V1.0.0
  contact:
    name: Dragon丿Z
    email: wula@hanhan
    url:
